title: Cayman Blog Theme
description: >-
  Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and
  Gitlab/GitHub Pages.
show_downloads: true
baseurl: ''
url: ''
google_analytics: null
cayman-blog:
  date_format: '%b %-d, %Y'
theme: null
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
plugins:
  - jekyll-target-blank
target-blank:
  rel: nofollow
header_page_refs:
  - now
  - about
  - contact
